### ISSUE TITLE
Automatically select dependent methods

### ISSUE THREAD

**Issue by JoeAtHPI** [hpi-swa-teaching/MorphicAPIExplorer#10]
There are certain methods in the Exploration View like `shadowColor:` which don't have any effect on the morph unless the user selects `addDropShadow` beforehand. To avoid confusion for these kind of methods, they should automatically select their dependent methods when clicked on.

**Comment by Zyranix** [comment]
Currently, we highlight dependencies on hover. We think this is good enough, but a change with automatically selecting should be easy now with the given architecture (maybe even implement an option for it?)

**Comment by Zyranix** [comment]
We think of the Morphplorer as an environment for learning the usage with morphs. If the methods would be selected automatically, the learning effect would be drastically decreased compared to doing it actively.
