### ISSUE TITLE
Save morph state inside a category

### ISSUE THREAD

**Issue by JoeAtHPI** [hpi-swa-teaching/MorphicAPIExplorer#11]
As of now, when a user clicks on a category, it's always reset to a clear state. This could be really frustrating for users that simply forgot to copy their code beforehand and have to recreate their prior state by hand.  There should be an option to save the methods one has currently selected which they can recall anytime inside the same category.

**Comment by Zyranix** [comment]
We can save morphs now and load them into other categories.
