### ISSUE TITLE
Right click on categories not disabled

### ISSUE THREAD

**Issue by postmartem** [hpi-swa-teaching/MorphicAPIExplorer#16]
- right clicking on categories selects categories and adds non existing code
- right clicking and dragging leads to even more weird behaviour instead of throwing an unsupported error. 
![grafik](https://user-images.githubusercontent.com/67064988/118104078-f3d50b00-b3da-11eb-84ce-efef16daed43.png)

**Comment by Zyranix** [comment]
Right clicking and dragging now doesn't lead to an error anymore, and the tree doesn't get "red". Did someone change something actively?

**Comment by JanFehse** [comment]
Fixed!
