### ISSUE TITLE
Search in Overview Window

### ISSUE THREAD

**Issue by bonifacyj** [hpi-swa-teaching/MorphicAPIExplorer#2]
**Current state**

This is the overview window, it displays all the categories of methods we have in our tool. At the moment, if I want to find a particular method, I have to guess to which category it belongs and then open the category and skim through it looking for a suitable method.
  
![image](https://user-images.githubusercontent.com/16317364/61734923-2a174580-ad83-11e9-8c6c-4106532ff73c.png)

**Desired state**

It would be great to have a search bar in the overview window so that a user can search through supported methods/morphs

**Comment by bonifacyj** [comment]
**Another possible user story** builds upon this one:
if a method I'm looking for is found inside of one of the categories, it would be great to have that category highlighted

**Comment by taminob** [comment]
merged in #22
