### ISSUE TITLE
Outsource pictures in MEXResources

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#40]
Because of the pictures being hardcoded as Arrays, the Methods are 1 MB of code each, and abhorrently slow down linting. One should try to load the pictures as a file, or at least as a string.

**Comment by JoeAtHPI** [comment]
You can tell the Linter to ignore certain methods. The drawback of extracting the hardcoded pics is that they aren't included in the image anymore and need additional outsourced resources. You have to include them when others are including this project as a baseline. Also, you have to load images from IO everytime one opens the Exploration View or executes a script saving the images once in a static variable. You could also just think about resizing the pics and loading smaller pics if you don't wanna change the linter, but changing the linter is probably the fastest solution to that issue

**Comment by Zyranix** [comment]
Currently, we already implemented the Do-Not-Lint-Class variant. Thanks for the input, I think we will just leave it with this solution then :D
