### ISSUE TITLE
Spacing of saved submorphs is wrong

### ISSUE THREAD

**Issue by PashPaul** [hpi-swa-teaching/MorphicAPIExplorer#44]
When you save a morph after adding a submorph to it, the gap between the morphs in the scrollpanel in the exploration view ist wrong.
![issue git](https://user-images.githubusercontent.com/68594232/122251085-7d8c6280-ceca-11eb-805e-c56fbf8b96d1.PNG)

**Comment by Zyranix** [comment]
User Story [2 HC]:
As a user I want to have the bug fixed that the spacing of the morphs in the exploration view is off when a morph with a submorph is added.
