### ISSUE TITLE
Where to use #changed:

### ISSUE THREAD

**Issue by Zyranix** [hpi-swa-teaching/MorphicAPIExplorer#59]
Currently, we sometimes use #changed: in an setter, and other times we do it manually in each method with corresponding (e.g. MEXExplorationView). We might want to have a look at it and standardize it ("what is the best practice?")

**Comment by kathrinthenhausen** [comment]
Changed: Eine Sache hat sich geändert, die View muss diese neu Abfragen 
Update: Eine Aktion muss als Reaktion auf eine Aktion aufgerufen werden

**Comment by Zyranix** [comment]
We don't want to use #changed in accessors and instead use it always in a method.
