### ISSUE TITLE
Method icons

### ISSUE THREAD

**Issue by Floriszenz** [hpi-swa-teaching/MorphicAPIExplorer#7]
We've introduced a class `MEXIcons` where a checkmark icon should be used to indicate whether a method in exploration view got selected or not.
It would be nice to actually use this icon for the list items

**Comment by Zyranix** [comment]
Our customer found a checkmark not useful and instead decreasing clarity, also regarding the fact that there are now other icons. If this will become relevant again, then this is a one-liner in the icon-method.
