### ISSUE TITLE
Apply changes for some special methods to see visual changes

### ISSUE THREAD

**Issue by Floriszenz** [hpi-swa-teaching/MorphicAPIExplorer#9]
For some methods like `#rotate:` or `#abandon`, currently when a user would select those methods to be applied on the morph, no changes are visible. The reason for this is that `#openInWorld:` is always the last method to be called on the morph when it's displayed in the playground.
It would be nice if a simple way could be found to make the changes visible.
A possible implementation might include changing the execution order so that `#openInWorld:` is executed and only after that the changes selected by the user are applied.

**Comment by JanFehse** [comment]
Is implementet, openInWorld is called before all other methods
